name: Node build, test and publish

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup stale actions
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: yarn
    - name: Enable docker layer cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Pull docker images
      run: docker-compose pull
      continue-on-error: true
    - name: Lint the source
      run: docker compose run --rm --no-TTY builder yarn lint
    - name: Transpile into dist
      run: docker compose run --rm --no-TTY builder yarn build
    - name: Run tests
      run: docker compose run --rm --no-TTY runner yarn test
    - name: Stop containers
      if: always()
      run: docker compose down

  publish-npm:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      issues: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SESAMECARE_OSS_NPM_TOKEN }}
        run: |
          yarn dlx semantic-release